# SPDX-FileCopyrightText: Copyright (c) 2025-2026 Igal Alkon
# SPDX-FileCopyrightText: Copyright (c) 2026 ALKONTEK <git@alkontek.com>
# SPDX-License-Identifier: BSD-3-Clause

# m.css configuration for Vecmat.
# https://mcss.mosra.cz/documentation/doxygen/
#
# python3 -m pip install jinja2 Pygments
# git clone --depth 1 https://github.com/mosra/m.css /tmp/m.css
# python3 /tmp/m.css/documentation/doxygen.py conf.py

DOXYFILE = 'Doxyfile-mcss'

MAIN_PROJECT_URL = 'https://github.com/alkavan/vecmat'

# Default m.css dark theme. Stylesheet path is resolved against doxygen.py
# (…/m.css/documentation/../css/…).

# Dark Theme
STYLESHEETS = [
    'https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i,600,600i%7CSource+Code+Pro:400,400i,600',
    '../css/m-dark+documentation.compiled.css',
]
THEME_COLOR = '#c0392b'
FAVICON = 'favicon-dark.png'

# Light Theme
#STYLESHEETS = [
#    'https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i,600,600i%7CSource+Code+Pro:400,400i,600',
#    '../css/m-light+documentation.compiled.css',
#]
#THEME_COLOR = '#cb4b16'
#FAVICON = 'favicon-light.png'

LINKS_NAVBAR1 = [
    ('Pages', 'pages', []),
    ('Files', 'files', []),
]
LINKS_NAVBAR2 = [
    ('Types', 'annotated', []),
    ('<a href="https://github.com/alkavan/vecmat">GitHub</a>', []),
]

# C sources still have many undocumented SIMD helpers. Keep them in the index.
SHOW_UNDOCUMENTED = True

# No LaTeX required for local builds.
M_MATH_RENDER_AS_CODE = True

FINE_PRINT = """
<p>Vecmat. BSD-3-Clause.
Copyright © <a href="https://alkontek.com">ALKONTEK</a>, 2025–2026.
Generated by <a href="https://doxygen.org/">Doxygen</a> {doxygen_version}
and <a href="https://mcss.mosra.cz/">m.css</a>.</p>
"""
